"""init4

Revision ID: 582454c9fda3
Revises: f9d317001222
Create Date: 2025-09-30 13:20:52.554923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582454c9fda3'
down_revision: Union[str, Sequence[str], None] = 'f9d317001222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remark_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('remark_item_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['remark_item_id'], ['remarks_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remark_item_id')
    )
    op.create_table('violation_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('violation_item_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('date_created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['violation_item_id'], ['violations_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('violation_item_id')
    )
    op.create_table('remark_answer_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['remark_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation_answer_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['violation_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation_answer_files')
    op.drop_table('remark_answer_files')
    op.drop_table('violation_answers')
    op.drop_table('remark_answers')
    # ### end Alembic commands ###
