"""init

Revision ID: 5c6afe51ee7a
Revises: 49ddb555efb4
Create Date: 2025-10-17 10:16:11.499545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c6afe51ee7a'
down_revision: Union[str, Sequence[str], None] = '49ddb555efb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Создаём новые таблицы
    op.create_table(
        'progress_work',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('percent', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('date_from', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('object_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'stage_progress_work',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('percent', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('status_main', sa.Enum('NOT_STARTED', 'WORK', 'PASSED', name='stage_progress_work_main_status_enum'), nullable=False),
        sa.Column('status_second', sa.Enum('NONE', 'AWAITING_VERIFICATION', 'VERIFICATION_REJECTED', name='stage_progress_work_second_status_enum'), nullable=False),
        sa.Column('date_from', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('kpgz', sa.String(length=255), nullable=False),
        sa.Column('volume', sa.Integer(), nullable=False),
        sa.Column('unit', sa.String(length=255), nullable=False),
        sa.Column('progress_work_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['progress_work_id'], ['progress_work.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'list_of_works',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('volume', sa.Integer(), nullable=False),
        sa.Column('desc', sa.Text(), nullable=False),
        sa.Column('stage_progress_work_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['stage_progress_work_id'], ['stage_progress_work.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'stage_progress_work_rejections',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('stage_progress_work_id', sa.UUID(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['stage_progress_work_id'], ['stage_progress_work.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'stage_progress_work_photos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('list_of_works_id', sa.UUID(), nullable=False),
        sa.Column('file_path', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['list_of_works_id'], ['list_of_works.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'stage_progress_work_rejection_photos',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('rejection_id', sa.UUID(), nullable=False),
        sa.Column('file_path', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['rejection_id'], ['stage_progress_work_rejections.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Сначала удаляем внешние ключи из materials
    op.drop_constraint(op.f('materials_object_id_fkey'), 'materials', type_='foreignkey')
    op.drop_constraint(op.f('materials_category_id_fkey'), 'materials', type_='foreignkey')

    # Теперь безопасно удаляем categories_materials
    op.drop_table('categories_materials')

    # Добавляем новую колонку и внешний ключ
    op.add_column('materials', sa.Column('stage_progress_work_id', sa.UUID(), nullable=False))
    op.create_foreign_key(
        None,
        'materials', 'stage_progress_work',
        ['stage_progress_work_id'], ['id'],
        ondelete='CASCADE'
    )

    # Удаляем старые колонки
    op.drop_column('materials', 'category_id')
    op.drop_column('materials', 'object_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('object_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('materials', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_category_id_fkey'), 'materials', 'categories_materials', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('materials_object_id_fkey'), 'materials', 'objects', ['object_id'], ['id'], ondelete='CASCADE')
    op.drop_column('materials', 'stage_progress_work_id')
    op.create_table('categories_materials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('date_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('date_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories_materials.id'], name=op.f('categories_materials_parent_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_materials_pkey'))
    )
    op.drop_table('stage_progress_work_rejection_photos')
    op.drop_table('stage_progress_work_photos')
    op.drop_table('stage_progress_work_rejections')
    op.drop_table('list_of_works')
    op.drop_table('stage_progress_work')
    op.drop_table('progress_work')
    # ### end Alembic commands ###
