"""init5

Revision ID: e1618f0daf84
Revises: 582454c9fda3
Create Date: 2025-09-30 16:36:18.914826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1618f0daf84'
down_revision: Union[str, Sequence[str], None] = '582454c9fda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation_answers', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('violation_answers', 'date_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation_answers', sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('violation_answers', 'created_at')
    # ### end Alembic commands ###
