"""init2

Revision ID: f3247d29925f
Revises: 5be1b7517951
Create Date: 2025-09-28 15:50:46.162220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3247d29925f'
down_revision: Union[str, Sequence[str], None] = '5be1b7517951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('date_from', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('date_to', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('request_number', sa.Text(), nullable=False),
    sa.Column('receiver', sa.Text(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('size', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Text(), nullable=False),
    sa.Column('net_weight', sa.Text(), nullable=False),
    sa.Column('gross_weight', sa.Text(), nullable=False),
    sa.Column('volume', sa.Text(), nullable=False),
    sa.Column('carrier', sa.Text(), nullable=False),
    sa.Column('vehicle', sa.Text(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('objects', sa.Column('contractor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'objects', 'company', ['contractor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('objects', 'is_contractor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('is_contractor', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.drop_column('objects', 'contractor_id')
    op.drop_table('materials')
    op.drop_table('categories_materials')
    # ### end Alembic commands ###
