services:
  db:
    image: cimg/postgres:17.6-postgis
    container_name: construct_db_dev
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - ./environments/.env.dev.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: construct_app_dev_image:latest
    container_name: construct_app_dev
    env_file:
      - ./environments/.env.dev.docker
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure:5
    networks:
      - app_network

volumes:
  postgresdata:

networks:
  app_network:
    driver: bridge
